### ISSUE TITLE
iv向量是什么？为什么在线工具不需要iv

### ISSUE THREAD

**Issue by xiaoyao20084321** [JadenTeng/ResourceCryptor#1]
你好，iv向量是什么？为什么在线工具不需要iv,只需要key和需要加密的数据
![image](https://user-images.githubusercontent.com/10344550/165695794-de43f90f-6e66-4674-850e-96ff16a704f6.png)

**Comment by jadenteng** [comment]
iv通过随机数（或伪随机）机制产生是一种比较常见的方法。iv的作用主要是用于产生密文的第一个block，以使最终生成的密文产生差异（明文相同的情况下），使密码攻击变得更为困难，除此之外iv并无其它用途。最大的好处是，即使相同的明文，相同的密钥，也能产生不同的密文。
